### ISSUE TITLE
Unique slugs are not being generated 

### ISSUE THREAD

**Issue by marcelxpfeifer** [raffaelj/cockpit_UniqueSlugs#4]
I'm not sure if I'm using the add-on wrong or what step I'm missing:

- I have installed the add-on 
- The add-on show up in my settings
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/40826752/199009861-92638d46-4e00-455d-bdf3-b1ab59506698.png">

- I have selected the column of the collection based on which the unique slug should be generated

---
Issue:
- Updated entries as well as new entires do not receive a unique slug

---
Cockpit Version: 0.12.2
Add-on version: 0.5.4

**Comment by raffaelj** [comment]
It should work... I prefer a config file, so I never use the GUI, but after checking the code, there shouldn't be any issue.

Does it work, if you set the configuration via `path/to/cockpit/config/config.php`?

```php
<?php
return [
    'app.name' => 'my app',

    'i18n' => 'de',
    'languages' => [
        'default' => 'Deutsch',
        'en' => 'English',
    ],

    'unique_slugs' => [
        'collections' => [
            'events' => 'name',
        ],
        'localize' => [
            'events' => 'name',
        ],
    ],

];
```

Other possibilities...:
The addon fires on save, so you have to save your entry first. Than the slug is generated.
Did you check your entry output via JSON inspector (also only available after saving the entry) or via REST api?

**Comment by marcelxpfeifer** [comment]
Thanks for the quick response I figured out the issue:
The first entry did not have a slug attribute (I think it was created before I added the plugin), so the following entries I create didn't detect it.
However even if I update the old entry the slug for this entry is not generated.

**Comment by raffaelj** [comment]
> However even if I update the old entry the slug for this entry is not generated.

That's a problem, but I changed it that way a while ago to prevent a different issue, see

*  https://github.com/raffaelj/cockpit_UniqueSlugs/issues/3
*  https://github.com/raffaelj/cockpit_UniqueSlugs/commit/d79c827e2e1d670960ec09139b81c669381835bc)

I have to think about a solution.

Workaround: Create a (visible) field of type text, name it slug and localize it. If you than save the old entry, it should send either an empty string or null, which will trigger the slug generation.

**Comment by marcelxpfeifer** [comment]
I guess that would work, but with a lot of old entries this would mean a lot of manual labor.

Would it be an option to add a button to the UI and a setting (initialize_slugs) to the config, which would generate all slug that do not exist.
The button would trigger the function and saving of the settings combined with the value set to true would also trigger the generation. 

This way we would not have to change the behavior on updating and saving of entries.
